from typing import Final

PLANET_IDS = {
    "Sun": 0,
    "Moon": 1,
    "Mars": 4,
    "Mercury": 2,
    "Jupiter": 5,
    "Venus": 3,
    "Saturn": 6,
    "Rahu": 11,
    "Ketu": -11,
}

UPAGRAHA_NAMES = {
    "Maandi": {
        "name_tamil": "மாந்தி",
        "name_english": "Maandi",
    }
}

PLANET_NAMES_TAMIL = {
    "Sun": "சூரியன்",
    "Moon": "சந்திரன்",
    "Mars": "செவ்வாய்",
    "Mercury": "புதன்",
    "Jupiter": "குரு",
    "Venus": "சுக்கிரன்",
    "Saturn": "சனி",
    "Rahu": "ராகு",
    "Ketu": "கேது",
    "Maandi": "மாந்தி",
}

PLANET_NAMES_ENGLISH = {
    "Sun": "Sun",
    "Moon": "Moon",
    "Mars": "Mars",
    "Mercury": "Mercury",
    "Jupiter": "Jupiter",
    "Venus": "Venus",
    "Saturn": "Saturn",
    "Rahu": "Rahu",
    "Ketu": "Ketu",
}

SIGNS_TAMIL = [
    "மேஷம்",
    "ரிஷபம்",
    "மிதுனம்",
    "கடகம்",
    "சிம்மம்",
    "கன்னி",
    "துலாம்",
    "விருச்சிகம்",
    "தனுசு",
    "மகரம்",
    "கும்பம்",
    "மீனம்",
]

SIGNS_ENGLISH = [
    "Aries",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarius",
    "Pisces",
]

SIGN_RULERS = [
    "Mars",
    "Venus",
    "Mercury",
    "Moon",
    "Sun",
    "Mercury",
    "Venus",
    "Mars",
    "Jupiter",
    "Saturn",
    "Saturn",
    "Jupiter",
]

NAKSHATRAS_TAMIL = [
    "அஸ்வினி",
    "பரணி",
    "கார்த்திகை",
    "ரோகிணி",
    "மிருகசீரிஷம்",
    "திருவாதிரை",
    "புனர்பூசம்",
    "பூசம்",
    "ஆயில்யம்",
    "மகம்",
    "பூரம்",
    "உத்திரம்",
    "ஹஸ்தம்",
    "சித்திரை",
    "சுவாதி",
    "விசாகம்",
    "அனுஷம்",
    "கேட்டை",
    "மூலம்",
    "பூராடம்",
    "உத்திராடம்",
    "திருவோணம்",
    "அவிட்டம்",
    "சதயம்",
    "பூரட்டாதி",
    "உத்திரட்டாதி",
    "ரேவதி",
]

NAKSHATRAS_ENGLISH = [
    "Ashwini",
    "Bharani",
    "Krittika",
    "Rohini",
    "Mrigashirsha",
    "Ardra",
    "Punarvasu",
    "Pushya",
    "Ashlesha",
    "Magha",
    "Purva Phalguni",
    "Uttara Phalguni",
    "Hasta",
    "Chitra",
    "Swati",
    "Vishakha",
    "Anuradha",
    "Jyeshtha",
    "Mula",
    "Purva Ashadha",
    "Uttara Ashadha",
    "Shravana",
    "Dhanishtha",
    "Shatabhisha",
    "Purva Bhadrapada",
    "Uttara Bhadrapada",
    "Revati",
]

YOGAS_TAMIL = [
    "விஷ்கம்பம்",
    "ப்ரீதி",
    "ஆயுஷ்மான்",
    "சௌபாக்யம்",
    "சோபனம்",
    "அதிகண்டம்",
    "சுகர்மம்",
    "த்ருதி",
    "சூலம்",
    "கண்டம்",
    "வ்ருத்தி",
    "த்ருவம்",
    "வ்யாகாதம்",
    "ஹர்ஷணம்",
    "வஜ்ரம்",
    "சித்தி",
    "வ்யதீபாதம்",
    "வரீயான்",
    "பரிகம்",
    "சிவம்",
    "சித்தம்",
    "சாத்யம்",
    "சுபம்",
    "சுக்லம்",
    "ப்ரஹ்மம்",
    "இந்திரம்",
    "வைத்ருதி",
]

YOGAS_ENGLISH = [
    "Vishkambha",
    "Preeti",
    "Ayushman",
    "Saubhagya",
    "Shobhana",
    "Atiganda",
    "Sukarma",
    "Dhriti",
    "Shoola",
    "Ganda",
    "Vriddhi",
    "Dhruva",
    "Vyaghata",
    "Harshana",
    "Vajra",
    "Siddhi",
    "Vyatipata",
    "Variyana",
    "Parigha",
    "Shiva",
    "Siddha",
    "Sadhya",
    "Shubha",
    "Shukla",
    "Brahma",
    "Indra",
    "Vaidhriti",
]

THITHI_TAMIL = [
    "சுக்ல பிரதமை",
    "சுக்ல துவிதியை",
    "சுக்ல திரிதியை",
    "சுக்ல சதுர்த்தி",
    "சுக்ல பஞ்சமி",
    "சுக்ல சஷ்டி",
    "சுக்ல சப்தமி",
    "சுக்ல அஷ்டமி",
    "சுக்ல நவமி",
    "சுக்ல தசமி",
    "சுக்ல ஏகாதசி",
    "சுக்ல துவாதசி",
    "சுக்ல திரயோதசி",
    "சுக்ல சதுர்த்தசி",
    "பௌர்ணமி",

    "கிருஷ்ண பிரதமை",
    "கிருஷ்ண துவிதியை",
    "கிருஷ்ண திரிதியை",
    "கிருஷ்ண சதுர்த்தி",
    "கிருஷ்ண பஞ்சமி",
    "கிருஷ்ண சஷ்டி",
    "கிருஷ்ண சப்தமி",
    "கிருஷ்ண அஷ்டமி",
    "கிருஷ்ண நவமி",
    "கிருஷ்ண தசமி",
    "கிருஷ்ண ஏகாதசி",
    "கிருஷ்ண துவாதசி",
    "கிருஷ்ண திரயோதசி",
    "கிருஷ்ண சதுர்த்தசி",
    "அமாவாசை",
]

THITHI_ENGLISH = [
    "Shukla Pratipada",
    "Shukla Dwitiya",
    "Shukla Tritiya",
    "Shukla Chaturthi",
    "Shukla Panchami",
    "Shukla Shashthi",
    "Shukla Saptami",
    "Shukla Ashtami",
    "Shukla Navami",
    "Shukla Dashami",
    "Shukla Ekadashi",
    "Shukla Dwadashi",
    "Shukla Trayodashi",
    "Shukla Chaturdashi",
    "Purnima",

    "Krishna Pratipada",
    "Krishna Dwitiya",
    "Krishna Tritiya",
    "Krishna Chaturthi",
    "Krishna Panchami",
    "Krishna Shashthi",
    "Krishna Saptami",
    "Krishna Ashtami",
    "Krishna Navami",
    "Krishna Dashami",
    "Krishna Ekadashi",
    "Krishna Dwadashi",
    "Krishna Trayodashi",
    "Krishna Chaturdashi",
    "Amavasya",
]

KARANA_TAMIL = [
    "பவம்",
    "பாலவம்",
    "கௌலவம்",
    "தைதுலை",
    "கரசை",
    "வணிசை",
    "பத்திரை",
    "சகுனி",
    "சதுஷ்பாதம்",
    "நாகவம்",
    "கிம்ஸ்துக்னம்"
]

KARANA_ENGLISH = [
    "Bava",
    "Balava",
    "Kaulava",
    "Taitila",
    "Gara",
    "Vanija",
    "Vishti",
    "Shakuni",
    "Chatushpada",
    "Naga",
    "Kimstughna"
]

DOB_to_DAY = {
    "Monday": "திங்கள்",
    "Tuesday": "செவ்வாய்",
    "Wednesday": "புதன்",
    "Thursday": "வியாழன்",
    "Friday": "வெள்ளி",
    "Saturday": "சனி",
    "Sunday": "ஞாயிறு",
}

VIMSHOTTARI_YEARS_TAMIL = {
    "கேது": 7,
    "சுக்கிரன்": 20,
    "சூரியன்": 6,
    "சந்திரன்": 10,
    "செவ்வாய்": 7,
    "ராகு": 18,
    "குரு": 16,
    "சனி": 19,
    "புதன்": 17,
}

VIMSHOTTARI_SEQUENCE_TAMIL = [
    "கேது",
    "சுக்கிரன்",
    "சூரியன்",
    "சந்திரன்",
    "செவ்வாய்",
    "ராகு",
    "குரு",
    "சனி",
    "புதன்",
]

NAKSHATRA_LORDS_TAMIL = [
    "கேது",
    "சுக்கிரன்",
    "சூரியன்",
    "சந்திரன்",
    "செவ்வாய்",
    "ராகு",
    "குரு",
    "சனி",
    "புதன்",
    "கேது",
    "சுக்கிரன்",
    "சூரியன்",
    "சந்திரன்",
    "செவ்வாய்",
    "ராகு",
    "குரு",
    "சனி",
    "புதன்",
    "கேது",
    "சுக்கிரன்",
    "சூரியன்",
    "சந்திரன்",
    "செவ்வாய்",
    "ராகு",
    "குரு",
    "சனி",
    "புதன்",
]

TAMIL_SOLAR_MONTHS = {
    0: "சித்திரை",
    1: "வைகாசி",
    2: "ஆனி",
    3: "ஆடி",
    4: "ஆவணி",
    5: "புரட்டாசி",
    6: "ஐப்பசி",
    7: "கார்த்திகை",
    8: "மார்கழி",
    9: "தை",
    10: "மாசி",
    11: "பங்குனி",
}

WEEKLY_LORDS = [
    "Sun",
    "Moon",
    "Mars",
    "Mercury",
    "Jupiter",
    "Venus",
    "Saturn",
]

GENDER_TAMIL = {
    "male": "ஆண்",
    "female": "பெண்",
}

RELATIONSHIP_NAMES_TAMIL = {
    "Father": "தந்தை",
    "Mother": "தாய்",
    "Elder Brother": "மூத்த சகோதரர்",
    "Younger Brother": "இளைய சகோதரர்",
    "Elder Sister": "மூத்த சகோதரி",
    "Younger Sister": "இளைய சகோதரி",
}

MARITAL_STATUS_TAMIL = {
    "Unmarried": "திருமணம் ஆகவில்லை",
    "Married": "திருமணமானவர்",
    "Widow": "விதவை",
    "Widower": "விதவர்",
    "Divorced": "விவாகரத்து",
}